### ISSUE TITLE
stydy_tasks; error in code

### ISSUE THREAD

**Issue by vihlancevk** [vian96/study_tasks#3]
And hello again! In addition to the previous error in the code, I found another one:
if you do not call the constructor, then a log file will not be created, which will cause the program to crash when calling the set_log_file() function, since the behavior of the fclose(nullptr) function is uncertain.
_no constructor call
set_log_file("stack_logs", "w");_

**Comment by vian96** [comment]
Good evening! 
It's your second issue and I am very grateful for that. It will also be fixed in the next update.
Good luck!
